{% set name = "cyflann" %}
{% set version = "0.2.4" %}
{% set sha256 = "361012482bc8120784324587c9f61dad1264649661f1690bee2e9f8e3ba1d3cc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - export FLANN_DIR="$PREFIX"        # [unix]
    - set "FLANN_DIR=%LIBRARY_PREFIX%"  # [win]
    - python -m pip install --ignore-installed --no-deps .
    - 'python {{ environ["RECIPE_DIR"] }}/dump_dir.py'
  # Windows VC9 doesn't work yet:
  # https://github.com/dougalsutherland/cyflann/issues/27
  skip: true  # [win and vc==9]

requirements:
  build:
    - {{ pin_compatible('numpy') }}
    - {{ compiler('c') }}
  host:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - flann
    - cython
  run:
    - python
    - flann

test:
  imports:
    - cyflann
  commands:
    - pytest --pyargs cyflann
    - conda inspect linkages -p $PREFIX cyflann  # [not win]
    - conda inspect objects -p $PREFIX cyflann  # [osx]
  requires:
    - pyflann
    - cython
    - pytest

about:
  home: http://github.com/dougalsutherland/cyflann
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Cython interface to FLANN'
  description: |
    cyflann is a Cython interface to the FLANN library. Compared to
    the default pyflann interface, it allows you to run lots of independent
    searches without the GIL.
  dev_url: https://github.com/dougalsutherland/cyflann

extra:
  recipe-maintainers:
    - dougalsutherland
