{% set name = "cyflann" %}
{% set version = "0.2.3" %}
{% set sha256 = "a38cfdbaf7b4005f1f6ba417186f485483f78219bec5aa95f479f38551d234ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: python -m pip install --ignore-installed --no-deps .

requirements:
  build:
    - python
    - pip
    - toolchain
    - numpy 1.11.*
    - flann 1.9.1
    - cython
    - pkg-config  # [unix]
  run:
    - python
    - numpy >=1.11
    - flann 1.9.1
    - pkg-config  # [unix]

test:
  imports:
    - cyflann
  commands:
    - nosetests --exe cyflann
    - conda inspect linkages -p $PREFIX cyflann  # [not win]
    - conda inspect objects -p $PREFIX cyflann  # [win]
  requires:
    - pyflann
    - cython
    - nose

about:
  home: http://github.com/dougalsutherland/cyflann
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Cython interface to FLANN'
  description: |
    cyflann is a Cython interface to the FLANN library. Compared to
    the default pyflann interface, it allows you to run lots of independent
    searches without the GIL.
  dev_url: https://github.com/dougalsutherland/cyflann

extra:
  recipe-maintainers:
    - dougalsutherland
