{% set name = "cyflann" %}
{% set version = "0.2.5" %}
{% set sha256 = "a78c304f5d7bc78971bcfe8ce2e661027f5f2810b5b0d313bb9a60ded1b518b6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - export FLANN_DIR="$PREFIX"        # [unix]
    - set "FLANN_DIR=%LIBRARY_PREFIX%"  # [win]
    - "{{ PYTHON }} -m pip install . -vv"
    - '{{ PYTHON }} {{ environ["RECIPE_DIR"] }}/dump_dir.py'
  # Windows VC9 doesn't work yet:
  # https://github.com/djsutherland/cyflann/issues/27
  skip: true  # [win and vc==9]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - flann
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - flann

test:
  imports:
    - cyflann
  commands:
    - pytest --pyargs cyflann
    - conda inspect linkages -p $PREFIX cyflann  # [not win]
    - conda inspect objects -p $PREFIX cyflann  # [osx]
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pyflann
    - cython
    - pytest

about:
  home: http://github.com/djsutherland/cyflann
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Cython interface to FLANN'
  description: |
    cyflann is a Cython interface to the FLANN library. Compared to
    the default pyflann interface, it allows you to run lots of independent
    searches without the GIL.
  dev_url: https://github.com/djsutherland/cyflann

extra:
  recipe-maintainers:
    - djsutherland
