{% set name = "cyflann" %}
{% set version = "0.2.4" %}
{% set sha256 = "361012482bc8120784324587c9f61dad1264649661f1690bee2e9f8e3ba1d3cc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  # Windows should work, but flann recipe isn't built there yet.
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - numpy 1.8.*
    - flann 1.9.1
    - cython
    - pkg-config
  run:
    - python
    - numpy >=1.8
    - flann 1.9.1
    - pkg-config

test:
  imports:
    - cyflann
  commands:
    - nosetests --exe cyflann
    - conda inspect linkages -p $PREFIX cyflann  # [not win]
    - conda inspect objects -p $PREFIX cyflann  # [win]
  requires:
    - pyflann
    - cython
    - nose

about:
  home: http://github.com/dougalsutherland/cyflann
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Cython interface to FLANN'
  description: |
    cyflann is a Cython interface to the FLANN library. Compared to
    the default pyflann interface, it allows you to run lots of independent
    searches without the GIL.
  dev_url: https://github.com/dougalsutherland/cyflann

extra:
  recipe-maintainers:
    - dougalsutherland
