travis:
  secure:
    BINSTAR_TOKEN: fxHyDVZX7vCrpZG5QPfQLuMVZgpoJ8UjQTmRekSuCxbt3Y3cj+gi7L7Q5PIEGMjApMvjK4FqN91l8Vkk7cMHgJ8FScS89FWn5zBhqA7NFGUpoRgFdgjyDosolTpFKy5K6k+YcmVEMXurHN9UbZaecRHwhPvhPnN8ouVC2QOb9nfvRVmvVnCy7+gzPVsZY2HVOAI005RpyOYB15MvsUGewWwH0r9P9UwHgx4zv6I39xpoTusS40anICBhuyctBOhAe4JJW3uPBhE2oz9DnemkihHzjZLBv6zinPBCudWqOXpW5ugEs6Ry08y3FmwtOur6g2ccZZs7zluKBh0QFtkY6o9JGBRmwL8uUo1aGJngnFKmTGfUhN0hZ6u9aHNpVuO3y57Va7Oa4ClwkNe/xobJCpw7MDDwutJvZe8Oy2oJcsLu5L/gCR5WyUqlB909UsuGNUsnKWazmX7KDQV/C3c9F6pCfysQ8+tdsuIbyQ9+qcZgrzyYfW3dKNIy/aiJUxs+wl771G7m0gSypWNopuw4CqvQgEhruPOrbnHpI/fSsEQcRXNEhEWSPko61t2ufq8BmxCBDCnbdl2ICQG6wYF29mk+EzjqlruVPwBdJ2Fvh+X/a+RbrTLxcvEfmzlZSDFWriNsnDlTB4dIL8tkAc2qltwDCGLSpSQnIF2gjjzUQ7s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
